// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// Automatically generated by addcopyright.py at 01/29/2013
package org.apache.cloudstack.api;

import org.apache.cloudstack.api.command.admin.host.AddHostCmd;
import org.apache.cloudstack.api.response.HostResponse;

import com.cloud.baremetal.manager.BareMetalDiscoverer;

@APICommand(name = "addBaremetalHost", description = "add a baremetal host", responseObject = HostResponse.class,
        requestHasSensitiveInfo = false, responseHasSensitiveInfo = false)
public class AddBaremetalHostCmd extends AddHostCmd {

    @Parameter(name = ApiConstants.IP_ADDRESS, type = CommandType.STRING, description = "ip address intentionally allocated to this host after provisioning")
    private String vmIpAddress;

    @Parameter(name = ApiConstants.BAREMETAL_MAAS_NODE_ID, type = CommandType.STRING, description = "MaaS unique ID of this host")
    private String baremetalUniqueId;

    @Parameter(name = ApiConstants.CPU_NUMBER, type = CommandType.STRING, description = "number of CPU cores of this host")
    private String baremetalCpuCores;

    @Parameter(name = ApiConstants.CPU_SPEED, type = CommandType.STRING, description = "CPU speed of this host")
    private String baremetalCpu;

    @Parameter(name = ApiConstants.MEMORY, type = CommandType.STRING, description = "memory capacity of this host")
    private String baremetalMemory;

    @Parameter(name = ApiConstants.HOST_MAC, type = CommandType.STRING, description = "MAC address of this host")
    private String baremetalMAC;

    public AddBaremetalHostCmd() {
    }

    public String getVmIpAddress() {
        return vmIpAddress;
    }

    public void setVmIpAddress(String vmIpAddress) {
        this.vmIpAddress = vmIpAddress;
    }

    public String getBaremetalUniqueId() {
        return baremetalUniqueId;
    }

    public String getBaremetalCpuCores() {
        return baremetalCpuCores;
    }

    public String getBaremetalCpu() {
        return baremetalCpu;
    }

    public String getBaremetalMemory() {
        return baremetalMemory;
    }

    public String getBaremetalMAC() {
        return baremetalMAC;
    }

    @Override
    public void execute() {
        this.getFullUrlParams().put(ApiConstants.BAREMETAL_DISCOVER_NAME, BareMetalDiscoverer.class.getName());
        super.execute();
    }
}
