// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// Automatically generated by addcopyright.py at 01/29/2013
// Apache License, Version 2.0 (the "License"); you may not use this
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// Automatically generated by addcopyright.py at 04/03/2012
package org.apache.cloudstack.compute.maas.api;

import java.util.List;

import javax.inject.Inject;

import org.apache.cloudstack.acl.RoleType;
import org.apache.cloudstack.api.APICommand;
import org.apache.cloudstack.api.ApiErrorCode;
import org.apache.cloudstack.api.BaseListCmd;
import org.apache.cloudstack.api.ServerApiException;
import org.apache.cloudstack.api.response.ListResponse;
import org.apache.cloudstack.compute.maas.MaasInventoryResponse;
import org.apache.cloudstack.compute.maas.MaasManager;
import org.apache.log4j.Logger;

@APICommand(
        name = "listMaasInventory",
        description = "list baremetal maas inventory",
        responseObject = MaasInventoryResponse.class,
        requestHasSensitiveInfo = false,
        responseHasSensitiveInfo = false,
        authorized = {RoleType.Admin, RoleType.ResourceAdmin, RoleType.DomainAdmin}
)
public class ListMaasInventoryCmd extends BaseListCmd {
    private static final Logger LOGGER = Logger.getLogger(ListMaasInventoryCmd.class);
    private static final String NAME = "listmassinventoryresponse";

    @Inject
    private MaasManager manager;

    // ///////////////////////////////////////////////////
    // ////////////// API parameters /////////////////////
    // ///////////////////////////////////////////////////
//    @Parameter(name = ApiConstants.ID, type = CommandType.LONG, description = "DHCP server device ID")
//    private Long id;
//
//    @Parameter(name = ApiConstants.DHCP_SERVER_TYPE, type = CommandType.STRING, description = "Type of DHCP device")
//    private String deviceType;

    /////////////////////////////////////////////////////
    /////////////////// Accessors ///////////////////////
    /////////////////////////////////////////////////////
//    public Long getClusterId() {
//        return clusterId;
//    }
//
//    public Long getId() {
//        return id;
//    }

    /////////////////////////////////////////////////////
    /////////////// API Implementation///////////////////
    /////////////////////////////////////////////////////
    @Override
    public void execute() {
        try {
            ListResponse<MaasInventoryResponse> response = new ListResponse<MaasInventoryResponse>();
            List<MaasInventoryResponse> responses = manager.listMaasInventory(this);
            response.setResponses(responses);
            response.setResponseName(getCommandName());
            response.setObjectName("massinventory");
            this.setResponseObject(response);
        } catch (Exception e) {
            LOGGER.debug("Exception happend while executing ListMaasInventoryCmd");
            throw new ServerApiException(ApiErrorCode.INTERNAL_ERROR, e.getMessage());
        }
    }

    @Override
    public String getCommandName() {
        return NAME;
    }
}
