// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// Automatically generated by addcopyright.py at 01/29/2013
package org.apache.cloudstack.compute.maas;

import com.google.gson.annotations.SerializedName;

import org.apache.cloudstack.api.ApiConstants;
import org.apache.cloudstack.api.BaseResponse;
import org.apache.cloudstack.api.EntityReference;

import com.cloud.serializer.Param;

@EntityReference(value = MaasInventoryResponse.class)
public class MaasInventoryResponse extends BaseResponse {
    @SerializedName(ApiConstants.ID)
    @Param(description = "device id of ")
    private String id;

    @SerializedName(ApiConstants.BAREMETAL_MAAS_CPU_COUNT)
    @Param(description = "the physical network to which this external dhcp device belongs to")
    private Integer cpuCount;

    @SerializedName(ApiConstants.BAREMETAL_MAAS_CPU_SPEED)
    @Param(description = "name of the provider")
    private Long cpuSpeed;

    @SerializedName(ApiConstants.BAREMETAL_MAAS_MEMORY)
    @Param(description = "name of the provider")
    private Long memory;

    @SerializedName(ApiConstants.BAREMETAL_MAAS_STORAGE)
    @Param(description = "url")
    private Double storage;

    public Integer getCpuCount() {
        return cpuCount;
    }

    public void setCpuCount(Integer cpuCount) {
        this.cpuCount = cpuCount;
    }

    public Long getCpuSpeed() {
        return cpuSpeed;
    }

    public void setCpuSpeed(Long cpuSpeed) {
        this.cpuSpeed = cpuSpeed;
    }

    public Long getMemory() {
        return memory;
    }

    public void setMemory(Long memory) {
        this.memory = memory;
    }

    public Double getStorage() {
        return storage;
    }

    public void setStorage(Double storage) {
        this.storage = storage;
    }
}
