// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// Automatically generated by addcopyright.py at 01/29/2013
package org.apache.cloudstack.compute.maas;

import com.google.gson.annotations.SerializedName;

import org.apache.cloudstack.api.ApiConstants;
import org.apache.cloudstack.api.BaseResponse;
import org.apache.cloudstack.api.EntityReference;

import com.cloud.serializer.Param;

@EntityReference(value = MaasServiceOfferingsResponse.class)
public class MaasServiceOfferingsResponse extends BaseResponse {
    @SerializedName(ApiConstants.BAREMETAL_MAAS_OFFERING_ID)
    @Param(description = "service offering id")
    private String offeringId;

    @SerializedName(ApiConstants.BAREMETAL_MAAS_OFFERING_NAME)
    @Param(description = "TODO")
    private String offeringName;

    @SerializedName(ApiConstants.BAREMETAL_MAAS_AVIALBALE_COUNT)
    @Param(description = "TODO")
    private Integer available;

    @SerializedName(ApiConstants.BAREMETAL_MAAS_TOTAL_COUNT)
    @Param(description = "TODO")
    private Integer total;

    @SerializedName(ApiConstants.BAREMETAL_MAAS_ERASING_COUNT)
    @Param(description = "TODO")
    private Integer erasing;

    public String getOfferingId() {
        return offeringId;
    }

    public void setOfferingId(String offeringId) {
        this.offeringId = offeringId;
    }

    public String getOfferingName() {
        return offeringName;
    }

    public void setOfferingName(String offeringName) {
        this.offeringName = offeringName;
    }

    public Integer getAvailable() {
        return available;
    }

    public void setAvailable(Integer available) {
        this.available = available;
    }

    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public Integer getErasing() {
        return erasing;
    }

    public void setErasing(Integer erasing) {
        this.erasing = erasing;
    }
}
